import { buildAuthHeaders } from "@/lib/api/client";

/**
 * Uploads a file directly to Cloudinary using a signature generated by the backend.
 * @param file The file to upload.
 * @param token Auth token.
 * @returns The secure URL of the uploaded image.
 */
export async function uploadToCloudinary(
  file: File,
  token: string
): Promise<string> {
  const timestamp = Math.floor(Date.now() / 1000);
  const publicId = `media_${Date.now()}_${Math.random().toString(36).substring(2, 8)}`;

  // 1. Get signature from backend
  const signatureUrl = `/api/v1/media/cloudinary-signature?publicId=${publicId}&timestamp=${timestamp}`;
  const sigResponse = await fetch(signatureUrl, {
    method: "GET",
    headers: buildAuthHeaders(token) as any,
  });

  if (!sigResponse.ok) {
    const errorData = (await sigResponse.json().catch(() => null)) as any;
    throw new Error(
      errorData?.error || "Error al obtener la firma de Cloudinary"
    );
  }

  const { signature, apiKey, cloudName } = await sigResponse.json();

  // 2. Upload to Cloudinary
  const formData = new FormData();
  formData.append("file", file);
  formData.append("api_key", apiKey);
  formData.append("timestamp", String(timestamp));
  formData.append("public_id", publicId);
  formData.append("signature", signature);
  formData.append("signature_algorithm", "sha256");

  const cloudinaryUrl = `https://api.cloudinary.com/v1_1/${cloudName}/image/upload`;
  const uploadResponse = await fetch(cloudinaryUrl, {
    method: "POST",
    body: formData,
  });

  if (!uploadResponse.ok) {
    const errData = (await uploadResponse.json().catch(() => null)) as any;
    console.error("Cloudinary error:", errData);
    throw new Error(
      errData?.error?.message || "Error al subir imagen a Cloudinary"
    );
  }

  const uploadResult = await uploadResponse.json();
  return uploadResult.secure_url;
}
